#:schema node_modules/wrangler/config-schema.json
name = "gal_hotel_compras_app"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "gal_hotel_compras_db_local"
database_id = "local"
